#+title: Conferência - tema jurisdiction
#+date: 27 de janeiro de 2023
#+author: João Gomes de Almeida
#+options: toc:nil num:nil
#+cite_export: csl

* Slide 1

Good morning. I would like to thank the organisers, Professors Paula Távora Vítor and Dulce Lopes for inviting me to such a wonderful event.

I would also like to greet my fellow colleagues on this panel and all the speakers. It is quite the honor to be in the same panel as Professors Cristina González-Beilfuss and Helena Mota.

Finally I would like to greet the audience.

I was asked to address jurisdiction in the new Brussels IIb. I'm following Professor Cristina González-Beilfuss, which is never easy, so will try to be brief, so we can better approach the Brussels IIb novelties in the debate that follows.

* Slide 2

Brussels IIb is a dual regulation concerning the rules on jurisdiction, as it provides rules on matrimonial matters and parental responsability.

No changes were made to the jurisdiction rules on matrimonial matters.

I'll give one example: the wording of article 4 is clearly too broad as it gives jurisdiction to the court seized in matrimonial matters to examine a counterclaim /insofar as that counterclaim falls within the scope of the Regulation/. The scope of the Regulation encompasses parental responsability. Does this mean that the court seized in matrimonial matters would have jurisdiction to rule on parental responsibility if it is brought as a counterclaim? That interpretation cannot stand considering the rules on parental responsability, namely articles 7 and 10. Even so, no change was made.

Regarding the main rules of jurisdiction in matrimonial matters, the recent developments were made by the European Court of Justice as the Court addressed the concept of habitual residence of the spouses in two rulings:
- Case C-289/20, /IB v. FA/, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-289%252F20&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=pt&lg=&page=1&cid=7960][EU:C:2021:955]] (25 November 2021); and
- Case C-501/20, /MPA/, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-501%252F20&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=pt&lg=&page=1&cid=7960][EU:C:2022:619]] (1 August 2022).

Very briefly, in the first case the Court ruled that a spouse can only have one habitual residence at a given time and for the first time elaborated on how to determine the habitual residence of a spouse. The case is also interesting because of paragraphs 59 to 61 of the decision, in which the European Court of Justice gives its opinion regarding the determination of the habitual residence of the spouse in question, nevertheless mentioning that it is for the refering court to ascertain and rule on that matter.

In the second case, both spouses (a spanish and a portugese national) work for the European Union and live in a non-European Union Country because of that work. The spanish spouse brought divorce proceedings before the spanish courts stating that her habitual residence was the one she had before she started working as a member of contract staff of the European Union. The refering court asked the European Court of Justice how the concept of habitual residence should be interpreted in the case of nationals of a Member State who are staying in a non-Member State by reason of the duties conferred on them as members of the contract staff of the European Union.

The European Court of Justice reinforced that habitual residence is characterised by two factors: (i) the /intention/ of the person concerned to establish the habitual centre of his or her interests in a particular place and (ii) a /presence which is sufficiently stable/ in the Member State concerned (paragraph 44). The European Court of Justice ruled that, considering the facts of the case, there was no presence as the spouses were physically absent permamently from the territory of Spain. The European Court of Justice ruled that one cannot establish an habitual residence without a sufficently stable presence, even in cases where the person concerned leaves the country because of its profissional activity.

* Slide 3

The relationship between arts. 6.º a 7.º of Brussels IIa Regulation was disputed.

The Sundelind Lopes ruling did not settle the matter (it didn't have to because the courts of another Member State had jurisdiction according to the Brussels IIa rules), but somewhat hinted, in paragraph 22 of the ruling, that art. 7.º must be read in conjunction with art. 6, both of Brussels IIa.

This was made obvious in Brussels IIb with the merger of the two articles.

However, this was already the main interpretation before and, in the /MPA/ ruling, that I've already alluded to, the European Court of Justice confirmed it.

One of the questions asked by the referring Court to the European Court of Justice was if it could assert jurisdiction based on national law and article 7.º of the Brussels IIa Regulation when no court of another Member State had jurisdiction pursuant to the rules of the Regulation and the defendant is a national of another Member State.

The European Court of Justice clearly ruled that the court did not have jurisdiction in that case:

#+begin_quote
"(...) where a court of a Member State does not have jurisdiction to rule on an application for the dissolution of matrimonial ties under Articles 3 to 5 of Regulation No 2201/2003, Article 6 of that regulation prevents that court from declaring that it has jurisdiction under the rules on residual jurisdiction laid down by national law, in accordance with Article 7(1) of that regulation, where the respondent is a national of a Member State other than that of that court." (paragraph 85)
#+end_quote

As such, this clarification is welcome, but one cannot say that it is a novelty of Brussels IIb.

* Slide 4

Regarding jurisdiction, the novelties are in the rules concerning parental responsability.

The prorrogation of court regime (article 12 of Brussels IIa) evolves into a unitary regime of choice of court in Article 10 of Brussels IIb. This regime of choice of court is now the same, even when the parental responsability is anciliary to divorce proceedings.

The conditions to be met by the choice of court agreement are an evolution of those stated in article 12, no 3, of the Brussels IIa Regulation:
- The child must have a substancial connection with the Member State of the choosen court; to the non-exaustive list of substancial connections, Brussels IIb adds as a substancial connection the former habitual residence of the child;
- Following the Valcheva ruling, it is made clear that any holder of parental responsability must agree freely or expressly accept the jurisdiction; it is also made clear that the choice of court can be made /in the course of proceedings/ or prior to the seising of a court. The wording regarding the agreement is much improved when compared with article 12.º, no 3, (b) of the Brussels IIa Regulation.
- Finally, emphasis is given to the best interests of the child, as now it is stated in an autonomous condition that the agreement is only efective if the exercise of jurisdiction is in the best interests of the child. This is a discretionary power of the court and an analysis that has to be made on a case-by-case basis.

There is already a significant amount of debate regarding the new article 10.º.

Some questions seem easier to answer: each and every one of the conditions put forth by article 10, no. 1, must be met; but condition (a), regarding the substancial connection with the child, is met if any one of the subconditions stated or even if the child has a substancial connection that is different than the ones stated. One can say, looking at letter of article 10.º/1/(a) that the list is open ended and is alternative in nature.

Other questions are harder:

Regarding consent, article 10/1/(b)/(ii) provides that, for agreements made in the course of the proceedings, the court must verify that all the parties are informed of their right not to accept jurisdiction. Some authors advocate that this control by the judge of the parties awareness should be extended to agreements made prior to the proceedings[cite:@lupoi2021 p. 547].

Another question concerns article 10.º, n.º 4 which states that the jurisdiction conferred by a choice of court agreement made in the course of proceedings is exclusive. The Regulation is silent regarding the effects of a choice of court agreement made at the latest at the time the court is seised.

Some authors argue that those choice of court agreements are not exclusive[cite:@gonzalezbeilfuss2021a p. 107;@herranzballesteros2021 p. 241;@shuilleabhain2021 p. 127]; Other authors argue that these choice of court agreements can only be exclusive /after/ the choosen court verifies that the conditions of article 10.º/1/(a) are met[cite:@corneloup2020 p. 230;@goncalves2022a p. 59]; finally, the Pratice Guide seems to adopt the view that the parties can confer jurisdiction by way of an exclusive or non-exclusive choice of court agreement made in advance or, at the latest, at the time the court is seised[cite:@musseva2022 p. 80;@jose2020 p. 1272].

Besides the main difference between an exclusive and a non-exclusive choice of court agreement - an exclusive choice of court agreement confers jurisdiction to a court or courts of a Member State and deprives the courts of the remaining Member States of jurisdiction - their regime on Brussels IIb is also different concerning:

- the transfer of jurisdiction to a court of another Member State; the court that has jurisdiction based on an exclusive choice of court agreement cannot transfer its jurisdiction (art. 12.º/5); and
- the /lis pendens/ rules. Art. 20.º/ 4 and 5 are new and transpose to the Brussels IIb the anti-"Gasser" rules of Brussels Ia (art. 31.º/2). If a court is seised based on an exclusive choice of court agreement, the principle of the court first seised ceases to apply and the other courts must stay proceedings until the choosen court declares if he has jurisdiction.

Article 10.º/3 is also new and goes beyond the European Court of Justice case law. In case C-436/13, /E. v. B./, the European Court of Justice ruled that jurisdiction based on prorrogation (art. 12.º of Brussels IIa) ceases following a final judgment in the proceedings. The rationale for this solution seems to be the need to respect the requirement of proximity for any new proceedings. Article 10.º/3 makes that the default rule, but the parties can now agree otherwise and stipulate that agreement continues to be effective even after the making of a final judgment.

* Slide 5

The transfer of jurisdiction to a court of another Member State was provided for in Article 15.º of the Brussels IIa Regulation and most saw it as a provision inspired by the /forum non conveniens/ doctrine of common-law countries.

Brussels IIb fleshes out those rules in articles 12 and 13. Article 12 deals with the cases where a court in one Member State wishes to transfer its jurisdiction to a court of another Member State that he considers better placed to assess the best interests of the child in the case at hand. Article 13.º deals with the cases where a court of a Member State wishes to obtain jurisdiction as he considers himself better placed to assess the best interests of the child and, as such, he may request a transfer of jurisdiction from the court of the Member State of the habitual residence of the child.

The novelty in Article 12 (reflected also in Article 13) is the strengthening of the powers of the court. To initiate the transfer the Court no longer requires the colaboration of one of the parties, either by requesting the transfer or by accepting the transfer initiated by the court. This seems a welcome change, as it emphasizes the role of the court in assessing the best interests of the child.

Acording to Article 13 the court that wishes to obtain jurisdiction must request a transfer from a court of the Member State of the habitual residence of the child.

This appears to be a restriction /vis a vis/ article 15/1 and 2 (c) of the Brussels IIa Regulation and raises questions. In the Brussels IIa the courts of a Member State having jurisdiction as to the matter could, by way of exception, transfer it to a court of another Member State, namely upon application of said court. Brussels IIa, as such, did not distinguish between legal basis of jurisdiction.

The new article 13 appears to do so, as the court who whishes to obtain jurisdiction must request a transfer from a court of the Member State of the habitual residence of the child. Can the court of Member State A (that has no jurisdiction according to the provisions of the Regulation) ask the Court of Member State B (of the habitual residence of the child) for a transfer of jurisdiction, even when a court of Member State C has already been seized based on a non-exclusive choice of court agreement? Even if one anwsers positively, that does not seem to affect the jurisdiction of the court of Member State C, as the Court of Member State B can only transfer its own jurisdiction. One can question, why is it not possibile to ask for a transfer of jurisdiction from the court of another Member State when he has jurisdiction based either on Article 10 (non-exclusive choice of court), Article 11 (presence of the child) or even Article 14 (national law)[cite:@rodriguezvazquez2020 p. 721]?

This solution appears to be a directly inspired by the wording of article 9 of the Hague 1996 Child Protection Convention, without taking into account that, according to the Explanatory Report, the more restrictive wording appears to be an oversight[cite:@lagarde1996 p. 563, ponto 59].

* Slide 6

Article 97 is, in my opinion, good news as this provision allows for the operation of the transfer, choice of court and /lis pendens/ rules of the Hague 1996 Child Protection Convention in cases connected with a European Union Member State and a non-European Union Convention State.

Article 61 of the Brussels IIa Regulation pointed in the opposite direction, and it seems beyond doubt that Article 97 is a better solution in regard to the relations with Third States that are Parties to the Hague 1996 Child Protection Convention.

* Slide 7

No news in the rules of jurisdiction in matrimonial matters is bad news, in my opinion. These rules remain largely unchanged since the Brussels II Convention of 1998 and will probably remain unchanged until 2032, the year when the report on the /ex post/ evaluation of Brussels IIb is due.

I'm far from original in thinking and supporting a choice of court in matrimonial matters.

Altought article 6.º is a welcome clarification on how the residual rules of jurisdiction operate, it is still a complex rule and one that I don't think we need. Is it necessary to leave space for the Member State's internal rules of jurisdiction? This seems to be a rule that remains only because of tradition and because Brussels IIb has the honor of having as predecessors some of first European Union Regulations on private international law. The new regulations (maintenance, sucession and matrimonial property regimes) provide for a full and complete set of rules regarding jurisdiction. And I can't think of a reason not to adopt the same in the Brussels IIb.

This is also a nice segway to the rules of jurisdiction in parental responsability, as they too have a residual rule that seems dated.

The changes regarding jurisdiction in parental responsability are evolutionary and not revolutionary. They consider the case-law of the European Court of Justice and try to improve (and are mostly successful) on the rules of Brussels IIa.

One last word: I may seem overly critical of Brussels IIb for not changing the jurisdiction rules in matrimonial matters. However, one cannot forget that there was a political reason and a political historical context which, together with the need for unanimity, justifies the solution. A Brussels IIb that applies to all Member States (except Denmark) with no new rules on jurisdiction in matrimonial matters is far preferable to a new enhanced cooperation instrument that applies only to some Member States on top of the Brussels IIb.

* Slide 8

Thank you for your time and I hope we have a lively debate.

* Bibliography

#+print_bibliography:
